config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  devise_for :users, :skip => :sessions, :controllers => {:passwords => 'api/v1/users/passwords'}
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post "sign_in", :to => 'sessions#create'
      get "/portfolio/:id/rates", :to => "portfolios#rate"
      get "/portfolio/:id/comments", :to => "portfolios#comment"
      namespace :users do
        resources :passwords
        resources :registrations
        resources :confirmations
      end
      resources :rates, only: :create
      resources :comments, only: :create
      resources :categories
      resources :portfolios
      resources :image_uploaders, only: :create
    end
  end
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
  get "*path", :to => "static_pages#home"
end

app/views/header/_header_admin.html.erb
<header class="header headroom">
  <nav class="navbar-default navbar">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <li class="sr-only"><%= t "header.toggle" %></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
        </button>

        <div>
          <%= link_to image_tag("https://s.sachmem.com/public/images/common/logo-small.png"),
            admin_root_path, class: "logo" %>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to t("header.manage_user"), admin_users_url %></li>
          <li><%= link_to t("header.manage_comment"), Settings.sachmem_manage_comment_url %></li>
          <li><%= link_to t("header.manage_book_key"), Settings.sachmem_manage_book_key_url %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if active?(current_user) %>

              <%= link_to users_info_path do %>
                <%= image_tag(current_user.avatar.thumb.url, class: "img-rounded", height: "22px", width: "22px") %>
              <% end %>

            <% else %>

              <a disabled="disabled">
                <%= image_tag(current_user.avatar, class: "img-rounded", height: "22px", width: "22px") %>
              </a>

            <% end %>
          </li>

          <li class="dropdown">
            <a href="" class="text-header dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-caret-down"></i>
            </a>

            <ul class="dropdown-menu">
              <% if active?(current_user) %>
                <li><%= link_to t("header.account"), users_info_path %></li>
                <li role="separator" class="divider"></li>
              <% end %>

              <li><%= link_to t("header.log_out"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </nav>
</header>

app/views/header/_header_developer.html.erb
<header class="header headroom">
  <nav class="navbar-default navbar">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <li class="sr-only"><%= t "header.toggle" %></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
        </button>

        <div>
          <%= link_to image_tag("https://s.sachmem.com/public/images/common/logo-small.png"),
            root_path, class: "logo" %>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!--  -->
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if active?(current_user) %>

              <%= link_to users_info_path do %>
                <%= image_tag(current_user.avatar.thumb.url, class: "img-rounded", height: "22px", width: "22px") %>
              <% end %>

            <% else %>

              <a disabled="disabled">
                <%= image_tag(current_user.avatar, class: "img-rounded", height: "22px", width: "22px") %>
              </a>

            <% end %>
          </li>

          <li class="dropdown">
            <a href="" class="text-header dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-caret-down"></i>
            </a>

            <ul class="dropdown-menu">
              <% if active?(current_user) %>
                <li><%= link_to t("header.manage_comment"), Settings.sachmem_manage_comment_url %></li>
                <li><%= link_to t("header.manage_document"), Settings.sachmem_manage_document_url %></li>
                <li><%= link_to t("header.manage_guide_teacher"), Settings.sachmem_manage_guide_teacher_url %></li>
                <li><%= link_to t("header.manage_school"), admin_schools_path %></li>
                <li><%= link_to t("header.manage_client"), admin_clients_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to t("header.account"), users_info_path %></li>
              <% end %>

              <li><%= link_to t("header.log_out"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </nav>
</header>

app/views/header/_header_member.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1"
              aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag("logo.png"),
        root_path, class: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="">Home</a></li>

        <li class="dropdown">
          <ul class="dropdown-menu">
            <li>
            <a href="">Home</a>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="" class="text-header dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false">
            Home
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>Test
            </li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>

        </li>

        <li class="dropdown">
          <a href="" class="text-header dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu">


            <li><%= link_to t("header.log_out"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/header/_header_root.html.erb
<header class="header headroom">
  <nav class="navbar-default navbar">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <li class="sr-only"><%= t "header.toggle" %></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
          <li class="icon-bar"></li>
        </button>

        <div>
          <%= link_to image_tag("https://s.sachmem.com/public/images/common/logo-small.png"),
            admin_root_path, class: "logo" %>
        </div>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!--  -->
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if active?(current_user) %>

              <%= link_to users_info_path do %>
                <%= image_tag(current_user.avatar.thumb.url, class: "img-rounded", height: "22px", width: "22px") %>
              <% end %>

            <% else %>

              <a disabled="disabled">
                <%= image_tag(current_user.avatar, class: "img-rounded", height: "22px", width: "22px") %>
              </a>

            <% end %>
          </li>

          <li class="dropdown">
            <a href="" class="text-header dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-caret-down"></i>
            </a>

            <ul class="dropdown-menu">
              <% if active?(current_user) %>
                <li><%= link_to t("header.manage_book"), Settings.sachmem_manage_book_url %></li>
                <li><%= link_to t("header.manage_document"), Settings.sachmem_manage_document_url %></li>
                <li><%= link_to t("header.manage_comment"), Settings.sachmem_manage_comment_url %></li>
                <li><%= link_to t("header.manage_template"), Settings.sachmem_manage_template_url %></li>
                <li><%= link_to t("header.manage_guide_teacher"), Settings.sachmem_manage_guide_teacher_url %></li>
                <li><%= link_to t("header.manage_school"), admin_schools_path %></li>
                <li><%= link_to t("header.manage_client"), admin_clients_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to t("header.account"), users_info_path %></li>
              <% end %>

              <li><%= link_to t("header.log_out"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </nav>
</header>